### ISSUE TITLE
Issue with REDIS

### ISSUE THREAD

**Issue by KCorre** [reTHINK-project/dev-IdPServer#4]
> oidc-idp              | POST /login 302 73.144 ms - 46
oidc-idp              | Error: MISCONF Redis is configured to save RDB snapshots, but is currently not able to persist on disk. Commands that may modify the data set are disabled. Please check Redis logs for details about the error.
oidc-idp              |     at HiredisReplyParser.execute (/usr/src/app/node_modules/redis/lib/parser/hiredis.js:30:33)
oidc-idp              |     at RedisClient.on_data (/usr/src/app/node_modules/redis/index.js:547:27)
oidc-idp              |     at Socket.<anonymous> (/usr/src/app/node_modules/redis/index.js:102:14)
oidc-idp              |     at emitOne (events.js:96:13)
oidc-idp              |     at Socket.emit (events.js:188:7)
oidc-idp              |     at readableAddChunk (_stream_readable.js:176:18)
oidc-idp              |     at Socket.Readable.push (_stream_readable.js:134:10)
oidc-idp              |     at TCP.onread (net.js:551:20)

Deployment error on rethink.orange-labs.fr
Seems there is writing right issue on the harddrive or something like that.

**Comment by KCorre** [comment]
Fixed 

> docker rmi -f $(docker images | grep "<none>" | awk "{print \$3}")
